Repository BluEye-Robotics/ProtocolDefinitions, pull requests merged in 2025-06, with the labels that each got.

#201 Add MagneticDeclination msg definition
  protobuf_definitions/message_formats.proto
  protobuf_definitions/telemetry.proto
Labels: enhancement

#204 Update Google.Protobuf package
  Blueye.Protocol.Protobuf.csproj
Labels: dotnet

#205 Generate TypeScript npm package
  .github/workflows/ci-typescript.yaml
  README.md
  README.npm.md
Labels: automation
