Repository BluEye-Robotics/ProtocolDefinitions, pull requests merged in 2025-01, with the labels that each got.

#178 Imagenex 831L
  Blueye.Protocol.Protobuf.csproj
  protobuf_definitions/message_formats.proto
Labels: enhancement

#179 Add C550d and M370s multibeam sonars to device list
  protobuf_definitions/message_formats.proto
Labels: enhancement

#180 Add return code for SetPersistentStorageSettingsRep
  protobuf_definitions/req_rep.proto
Labels: enhancement

#181 Add custom markdown template
  markdown.tmpl
  protoc-gen-doc.sh
Labels: documentation

#182 Update dotnet packages and improve documentation
  Blueye.Protocol.Protobuf.csproj
  protobuf_definitions/message_formats.proto
Labels: documentation, dotnet

#183 Add multibeam error flags and improve documentation
  protobuf_definitions/aquatroll.proto
  protobuf_definitions/control.proto
  protobuf_definitions/message_formats.proto
  protobuf_definitions/mission_planning.proto
  protobuf_definitions/req_rep.proto
  protobuf_definitions/telemetry.proto
Labels: documentation, enhancement

#184 Add WaterLinked Sonar 3D-15
  protobuf_definitions/message_formats.proto
Labels: enhancement
